name: Run unit-tests

on:
- push
- pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7.x, 3.8.x, 3.9.x]
        pandas: [0.24.*, 0.25.*, 1.1.*, 1.2.*, 1.3.*]
        exclude:
          - python: 3.8.x # Unknown issue with this test.
            pandas: 0.24.*
          - python: 3.9.x
            pandas: 0.24.*
          - python: 3.9.x
            pandas: 0.25.*
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.in
        pip install -e .[full]
        pip install --upgrade numpy=="1.19.*"
        pip install --upgrade pandas=="${PANDAS_VERSION}"
      env:
        PANDAS_VERSION: ${{ matrix.pandas }}
    - name: Run tests
      run: pytest -v -s
